### ISSUE TITLE
USB连接异常

### ISSUE THREAD

**Issue by ADsuper** [Liuguihong/AndroidUsbSerialSdk#1]
使用方式：

```
mCommonUsbSerialSdk = CommonUsbSerialSdk(context)

        mCommonUsbSerialSdk!!.
            .setForceGrant(true) // 强制授权，授权不成功重复弹出授权弹窗
            .setPortType(PortType.USB) // 通信类型
            // 设置USB设备过滤条件
            .setDeviceFilter { usbDevice ->
                val productId = usbDevice.productId
                val vendorId = usbDevice.vendorId
                Log.i(TAG, "isTargetDevice: pid:$productId  vid:$vendorId")
                vendorId == vid && productId == pid
            }
            .setUsbSerialListener(object : UsbSerialListener {
                // 读写数据回调
                override fun onWrite(bytes: ByteArray) {
                    Log.i(TAG, "onWrite: " + String(bytes))
                }

                override fun onRead(bytes: ByteArray) {
                    Log.i(TAG, "onRead: ${HexUtil.bytesToHex(bytes)}")
                    usbSerialHelperListener.onReadData(bytes)
                }

                override fun onDeviceOpened(usbDevice: UsbDevice, success: Boolean) {
                    Log.i(TAG, "onDeviceOpened: $success")
                    mCommonUsbSerialSdk?.startThread()
                }
            })
            .create()

        mCommonUsbSerialSdk!!.checkTargetDevice() // 检查是否有目标设备
```

报错日志：
Could not get read & write endpoints

**Comment by Liuguihong** [comment]
自定义或者修改库里的CustomUsbPort，复写openInt和closeInt方法，找到对应设备的读写数据节点。

public class CustomUsbPort extends CommonUsbSerialPort {

    public CustomUsbPort(UsbDevice device, int portNumber) {
        super(device, portNumber);
    }

    @Override
    protected void openInt(UsbDeviceConnection connection) throws IOException {
        for (int i = 0; i < mDevice.getInterfaceCount(); i++) {
            UsbInterface usbIface = mDevice.getInterface(i);
            if (!mConnection.claimInterface(usbIface, true)) {
                throw new IOException("Could not claim data interface");
            }
        }

        UsbInterface dataIface = mDevice.getInterface(0);
        for (int i = 0; i < dataIface.getEndpointCount(); i++) {
            UsbEndpoint endpoint = dataIface.getEndpoint(i);
            if (endpoint.getDirection() == UsbConstants.USB_DIR_IN) {
                mReadEndpoint = endpoint;
            }
            if (endpoint.getDirection() == UsbConstants.USB_DIR_OUT) {
                mWriteEndpoint = endpoint;
            }
        }
    }

    @Override
    protected void closeInt() {
        try {
            for (int i = 0; i < mDevice.getInterfaceCount(); i++) {
                mConnection.releaseInterface(mDevice.getInterface(i));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public UsbSerialDriver getDriver() {
        return null;
    }

    @Override
    public void setParameters(int baudRate, int dataBits, int stopBits, int parity) throws IOException {
    }

    @Override
    public EnumSet<ControlLine> getControlLines() throws IOException {
        return null;
    }

    @Override
    public EnumSet<ControlLine> getSupportedControlLines() throws IOException {
        return null;
    }
}
